spring:
  application:
    name: config
  profiles:
    active: native #配置文件的获取方式
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared  #本地配置文件存放的路径
server:
  port: 8762
