server:
  port: 8030
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'